### ISSUE TITLE
Collabora editor UI language should follow the language of the UI of XWiki

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-collabora#28]
For a user editing an attachment of a french page in a french browser, it's expected that the UI of Collabora is in French, but today it's in English.

The good choice is probably the current UI language of XWiki, which may depend on multiple factors: on a monolingual wiki it is the language of the wiki regardless of the language of the document, on a multilanguage wiki it depends on the current chosen language.
The idea is that the Collabora UI should be coherent in terms of language with the XWiki UI.

**Comment by oanalavinia** [comment]
Couldn't find an answer on the documentation, but found one on their [forum](https://forum.collaboraonline.com/t/change-the-language-of-collabora-application-ui-programmatically/456)

**Note** that it's still needed for a language to be installed on the Collabora online server. If your wiki uses `fr_CA` but this locale is not installed, then it will fallback on the default language (which might be configurable, but it is `en` by default)

To configure the installed languages, please check their documentation. For example, for docker there is a list of languages (dictionaries) already installed https://sdk.collaboraonline.com/docs/installation/Docker_image.html?highlight=language#create-a-container-from-the-image-and-run-it with the possibility to add more, [here](https://sdk.collaboraonline.com/docs/installation/Installation_from_packages.html?highlight=locale#localization) is documentation for installation from packages and [in here](https://sdk.collaboraonline.com/docs/language_tool.html#libreoffice-core) you can see a starting point for where the language options might be on your Collabora server
