### ISSUE TITLE
Increase the default value for the Editing Token Timeout

### ISSUE THREAD

**Issue by LucianCheve** [xwikisas/application-collabora#46]
Currently, the default value for the Editing Token Timeout is 5 hours. There are plenty of cases in which the users work on the same document for the entirety of the day, and or leave the editor open for more than 5 hours. Once the Editing Token Timeout expires, the saves to the document made by the user no longer apply/register.

I propose to increase the value for the Editing Token Timeout to **48h.**

**Comment by lucaa** [comment]
@LucianCheve @oanalavinia is this value configurable somewhere?

The easiest would be to make it configurable so that the users can sync it with other timeouts that they may have (such as authentication session timeout or other).
