### ISSUE TITLE
Display to the user that their Editing Token Timeout has expired

### ISSUE THREAD

**Issue by LucianCheve** [xwikisas/application-collabora#47]
Currently, if the Editing Token Timeout expires, there is no way for the user to know. Not having this information, the user continues to edit the document, but even if they click the save icon, no saves are registered and there is no warning presented to the user that this is the case. At the end, the user believes he saved the document, but in reality this is not the case because the Editing Token Timeout expired.

Implement a way for the user to be notified that the Editing Token Timeout has expired.

Edit:
After more testing, I wish to add these details:
When the Edit Token Timeout expires, the users (I tested with 2) get the following message:
![image](https://github.com/xwikisas/application-collabora/assets/156320797/8dc11c2d-2bbe-4c4f-a63f-e37bdd188177)

This message was received by both users that had their token expire.

After you get the warning, you no longer can save, and you basically have 2 options:
1) Wait for the autosave to trigger (from my observations, it happens every 2-3 minutes), then leave the session and access it again to get a new token
2) From Collabora, go to File > Download and save the file on your computer. Exit and re-enter the Collabora session(which generates a new token) and add the not-saved content.

**Comment by oanalavinia** [comment]
This issue has been fixed so the token lifespan will be extended when possible. This means that if the user still has edit rights on the document, his token will be renewed automatically and he can continue editing without any manual operation (and without losing changes)
